name: SAST Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      run: bandit --skip B101 -r .